# name of the applied model
model_name: 'AvatarNet'

# the input sizes
content_size: 512
style_size: 512

# perceptual loss configurations
network_name: 'vgg_19'
checkpoint_path: '/DATA/lsheng/model_zoo/VGG/vgg_19.ckpt'
checkpoint_exclude_scopes: 'vgg_19/fc'
ignore_missing_vars: True

# style loss layers
style_loss_layers:
  - 'conv1/conv1_1'
  - 'conv2/conv2_1'
  - 'conv3/conv3_1'
  - 'conv4/conv4_1'

#################################
# style decorator specification #
#################################
# patch size for style decorator
patch_size: 5

# style encoding method
style_coding: 'ZCA' # 'AdaIN'

# style interpolation
style_interp: 'normalized'

####################
# training routine #
####################
training_image_size: 256
weight_decay: 0.0005
trainable_scopes: 'combined_decoder'

# loss weights
content_weight: 1.0
recons_weight: 10.0
tv_weight: 10.0
